#!/bin/sh

CMD=$2
shift

case $CMD in
    create)
        #create jail
        NAME=$2
        echo "Creating vanilla jail with name" $NAME
        ;;
    *)
        echo "Unknown command" $CMD
        ;;
esac

